### PR TITLE
Affine "combine" for dlog commitment

### PR DESCRIPTION
**Pull request by imeckler**
This PR implements the affine version of the combining function for the dlog commitment. Runtime is about 20-25% better than the previous best.

E.g.,

```
$ cargo test bench_combine --release -- --nocapture

combine 100000 7.490999722s
affine_window_combine 100000 5.190810545s
affine_combine 100000 6.07763902s
window_combine 100000 6.652958733s
```

The current best is `affine_window_combine`, the previous was `window_combine`.

### CODE REVIEW

**Comment by ltvvlz** [comment]
`pub fn affine_combine<P: SWModelParameters>(g1: &Vec<SWJAffine<P>>, g2: &Vec<SWJAffine<P>>, x1: P::ScalarField, x2: P::ScalarField) -> Vec<SWJAffine<P>> {
    const CHUNK_SIZE : usize = 10_000;
    let b : Vec<_> = g1.chunks(CHUNK_SIZE).zip(g2.chunks(CHUNK_SIZE)).collect();
    let v : Vec<_> = b.into_par_iter().map(|(v1, v2)| affine_combine_base(v1, v2, x1, x2)).collect();
    v.concat()
}`

CHUNK_SIZE=10_000. Too small array/chunk size can degrade the batched Affine addition benefit since it is best for the longer arrays. Also, too small thread jobs may result in suboptimal CPU parallelism since the jobs would be going up and down too often. It could be better to parallelize elsewhere and do the batched addition on longer arrays/chunks.

**Comment by ltvvlz** [comment]
`#![feature(test)]

extern crate test;
mod combine;
pub mod srs;
pub mod commitment;
`
This does not work for relase builds, looks to work only for noghtly.

**Comment by imeckler** [comment]
> `pub fn affine_combine<P: SWModelParameters>(g1: &Vec<SWJAffine<P>>, g2: &Vec<SWJAffine<P>>, x1: P::ScalarField, x2: P::ScalarField) -> Vec<SWJAffine<P>> { const CHUNK_SIZE : usize = 10_000; let b : Vec<_> = g1.chunks(CHUNK_SIZE).zip(g2.chunks(CHUNK_SIZE)).collect(); let v : Vec<_> = b.into_par_iter().map(|(v1, v2)| affine_combine_base(v1, v2, x1, x2)).collect(); v.concat() }`
> 
> CHUNK_SIZE=10_000. Too small array/chunk size can degrade the batched Affine addition benefit since it is best for the longer arrays. Also, too small thread jobs may result in suboptimal CPU parallelism since the jobs would be going up and down too often. It could be better to parallelize elsewhere and do the batched addition on longer arrays/chunks.

Hmm, given the structure of the prover and the commitment opening function, I'm not sure there is another place to parallelize. Do you have an idea in mind?

This chunk size had good performance in the 100,000 - 1,000,000 range which is of interest. Also, 10,000 seemed to be big enough that processing the whole array at once had similar performance to running this code with RAYON_NUM_THREADS=1.

Do you think we should set the chunk size dynamically somehow based on the input size?

**Comment by imeckler** [comment]
> `#![feature(test)]
> 
> extern crate test;
> mod combine;
> pub mod srs;
> pub mod commitment;
> `
> This does not work for relase builds, looks to work only for nightly.

Ah ok, I will move the tests around to get rid of this.

**Comment by ltvvlz** [comment]
> pub fn affine_combine<P: SWModelParameters>(g1: &Vec<SWJAffine<P>>, g2: &Vec<SWJAffine<P>>, x1: P::ScalarField, x2: P::ScalarField) -> Vec<SWJAffine<P>> { const CHUNK_SIZE : usize = 10_000; let b : Vec<_> = g1.chunks(CHUNK_SIZE).zip(g2.chunks(CHUNK_SIZE)).collect(); let v : Vec<_> = b.into_par_iter().map(|(v1, v2)| affine_combine_base(v1, v2, x1, x2)).collect(); v.concat() }
> CHUNK_SIZE=10_000. Too small array/chunk size can degrade the batched Affine addition benefit since it is best for the longer arrays. Also, too small thread jobs may result in suboptimal CPU parallelism since the jobs would be going up and down too often. It could be better to parallelize elsewhere and do the batched addition on longer arrays/chunks.
> 
> Hmm, given the structure of the prover and the commitment opening function, I'm not sure there is another place to parallelize. Do you have an idea in mind?
> This chunk size had good performance in the 100,000 - 1,000,000 range which is of interest. Also, 10,000 seemed to be big enough that processing the whole array at once had similar performance to running this code with RAYON_NUM_THREADS=1.
> Do you think we should set the chunk size dynamically somehow based on the input size?

My general understanding as well as the observations from the experimentation with multiexp suggest that it is more optimal to parallelize over larger jobs where threads execute as long as possible rather than over short jobs. Overall CPU utilization may drop when jobs are small. I do not know how the prover will be organized in the system. Do we consider a setup where prover has to compute few proofs in parallel ? If so, this could be a place to parallelize. Otherwise, I agree, it is not clear where else to parallelize.

In regards to the chunk size, how about using a chunk size which is the array length divided by the number of CPUs (let cpus = num_cpus::get(); from crate "num_cpus") ? If the number of CPUs is too large, then, possibly, set then set chunk size to something specific, like you do.

**Comment by imeckler** [comment]
> Do we consider a setup where prover has to compute few proofs in parallel ? If so, this could be a place to parallelize. Otherwise, I agree, it is not clear where else to parallelize.

The key speed metric is in just the single proof setting. The other setting is important as well, but the most important thing is driving down the single proof generation time.

> In regards to the chunk size, how about using a chunk size which is the array length divided by the number of CPUs (let cpus = num_cpus::get(); from crate "num_cpus") ?

Doesn't this have the potential to underutilize the CPU? When I run it, the CPU utilization appears to be total, and I think the fixed cost per chunk is pretty low if the chunk is at least a few thousand.

The theoretical best we could hope for is

(2 * affine-double + 1 * affine-add) / (2 * jacobian-double + 1 * jacobian-mixed-add)
=
(2 * 6 + 1 * 6) / (2 * 7 + 1 * 11) = 0.72.

We get pretty close to this so I think the parallelization strategy is good. 

Maybe more convincingly, the single-threaded performance advantage is essentially the same as the parallel one, so I don't think any issues are coming from the parallelization strategy.

**Comment by ltvvlz** [comment]
> > Do we consider a setup where prover has to compute few proofs in parallel ? If so, this could be a place to parallelize. Otherwise, I agree, it is not clear where else to parallelize.
> 
> The key speed metric is in just the single proof setting. The other setting is important as well, but the most important thing is driving down the single proof generation time.
> 
> > In regards to the chunk size, how about using a chunk size which is the array length divided by the number of CPUs (let cpus = num_cpus::get(); from crate "num_cpus") ?
> 
> Doesn't this have the potential to underutilize the CPU? When I run it, the CPU utilization appears to be total, and I think the fixed cost per chunk is pretty low if the chunk is at least a few thousand.
> 
> The single-threaded performance advantage (when we don't do any chunking at all) is essentially the same as the parallel one, so I don't think any issues are coming from the parallelization strategy or chunking.
> 
> Just for the record, the theoretical best we could hope for is roughly
> 
> ```
> (2 * affine-double + 1 * affine-add) / (2 * jacobian-double + 1 * jacobian-mixed-add)
> =
> (2 * 6 + 1 * 5) / (2 * 7 + 1 * 11) = 0.68.
> ```
> 
> (although this ignores the cost in producing the window tables, where I think we probably have an even bigger advantage)
> 
> The empirical advantage was 5.19 / 6.65 ~= 0.78 so definitely room for improvement, I just don't think it's coming from the parallelization strategy.

OK, I understand, makes sense. Since you have seen the benefit close to that of the singlethreaded case, it looks like it work well. As for underutilisation of CPU, as long as the chunk number is divisible by CPU number (even if one chunk per CPU) it does not look to be underutilised, especially, if the chunk length is, with this setup, longer. But again, since you saw the multithr  performance close to the optimal, it looks like your implementation is, at least, one of the optimal ones.

**Pull request merged**
